version: "3"
services:
  swagger-<meta.name>:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/mnt/swagger.json
    networks:
      - default
    volumes:
      - ./swagger.json:/mnt/swagger.json
    ports:
      - 8181:8080
